location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/mrs_modules_msgs
    name: mrs_modules_msgs
    rev: ros2
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: mrs_modules_msgs
    scripts:
      - git submodule update --init --recursive
