location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/mrs_modules_msgs
    name: mrs_modules_msgs
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_modules_msgs
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_utils
    name: mrs_utils
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_utils
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/trajectory_loader
    name: mrs_uav_trajectory_loader
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_trajectory_loader
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/path_loader
    name: mrs_uav_path_loader
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_path_loader
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_serial
    name: mrs_serial
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_serial
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_bumper
    name: mrs_bumper
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_bumper
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_pcl_tools
    name: mrs_pcl_tools
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_pcl_tools
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/ouster-ros
    name: ouster-ros
    rev: mrs
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/ouster-ros
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/nimbro_network
    name: nimbro_network
    rev: develop-deb
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/nimbro-network
    scripts:
      - git submodule update --init --recursive
